language: python
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "pipenv install --dev --system"
script:
script:
  - flake8
  - coverage run --include=./* --omit=test/* -m pytest
  - coverage report
