language: python
python:
  - "3.6"
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - flake8
  - coverage run --include=./* --omit=test/* -m pytest
  - coverage xml
  - python-codacy-coverage -r coverage.xml
